### PR TITLE
kotlin gr'adle build.gradle.kts

### PR DESCRIPTION
**Pull request by sylv256**

### CODE REVIEW

**Review by triphora — APPROVED** [review]

**Review by Mysterious-Dev — APPROVED** [review]

**Comment by sylv256** [comment]
wait don’t merge yet

**Comment by sylv256** [comment]
I have to fix something later when I get on c0mpu7er

**Comment by sylv256** [comment]
sorry, have been busy. will fix in a few days dw

**Review by sylv256 — COMMENTED** [review]
done

**Pull request closed without merging**
