### PR TITLE
Allow accessing uploadFile as a RegularFileProperty

### PR DESCRIPTION
**Pull request by jpenilla**
I found it quite confusing when I was unable to do either
```kotlin
uploadFile.set(tasks.shadowJar.flatMap { it.archiveFile })
// or
uploadFile.set(tasks.shadowJar)
```
due to overload resolution ambiguity.
In order to get it working I had to employ one of the following:
```kotlin
uploadFile.set(tasks.shadowJar.get())
// or
(uploadFile as Property<Task>).set(tasks.shadowJar)
```

With this change the old `Property<Object>` will continue to work as before, but a new method for accessing the property as a `RegularFileProperty` is now available, so `uploadFileProperty.set(tasks.shadowJar.flatMap { it.archiveFile })` will work as expected (with groovy this would be `uploadFileProperty.set(tasks.shadowJar.archiveFile)`). Additionally, it allows for auto task dependency wiring when using a non-`AbstractArchiveTask` task type.

If this change is accepted I think a similar change would be good to apply for the additional files.

### CODE REVIEW

**Review by triphora — COMMENTED** [review]
Looks good for the most part, but there seems to be quite a bit of wonkiness when it comes to formatting, could you fix this when you get a chance?

Also, `uploadFileProperty` is a bit of a strange name for people to set their properties to. Would it be better to just use a name like `file`? More likely than not I would remove the old `uploadFile` in Minotaur v3 and just use this new property.

**Comment by jpenilla** [comment]
I've renamed the property to `file`.

Could you point me to the formatting issues? I can't seem to find them.

**Comment by triphora** [comment]
Nevermind, I was misreading the code because I didn't notice a lambda. Formatting is fine.

Another thought, do you think it would be better to make this an array to put all files into (both primary and additional) or is that not possible with RegularFileProperty?

**Comment by jpenilla** [comment]
There is ConfigurableFileCollection but I don't think it has any contract about iteration order (and having them all in the same collection in user facing API when one is primary might be confusing ux). But using a ConfigurableFileCollection for additional files instead of a `ListProperty<Object>` would probably work.

And then for the task itself, they can all be dumped into the same collection since we get directly from the extension and only use the input collection for auto-task dependency wiring when enabled.

**Comment by triphora** [comment]
> But using a `ConfigurableFileCollection` for additional files instead of a `ListProperty<Object>` would probably work.

Alright, sounds good. Do you want me to get this PR merged and released now and I can add that at a later date, or would you rather implement this yourself in this PR?

**Comment by jpenilla** [comment]
Looking closer keeping the legacy property working won't be as straightforward for a file collection. So I think it's easiest to just merge this for now and handle the additional files in 3.0.

edit: Actually, might be fine, there's no `convention` but `from` will probably work well enough. Regardless would be convenient for me to have this merged and handle the additional files later

**Review by triphora — APPROVED** [review]

**Comment by ExpensiveKoala** [comment]
I understand that 2.7+ is supposed to be unstable, but can you please try to avoid breaking changes in minor versions?
Replacing `uploadFile` with `legacyUploadFile` breaks all projects using latest version with `uploadFile`.
Especially when the readme doesn't mention the change...

**Comment by triphora** [comment]
This shouldn't break anything that's using uploadFile?

**Comment by ExpensiveKoala** [comment]
The PR replaces the property `uploadFile` with `legacyUploadFile`. Does that not break it?

**Comment by triphora** [comment]
No, because that field is private. The API (the get methods) are unchanged.

**Comment by ExpensiveKoala** [comment]
I am not an expert on this subject, so correct me if I'm wrong...

The API (get methods) are for internal use by the plugin or anything written to extend the plugin. The properties defined in the extension class correspond to the properties you can set in your build.gradle.
Take the example from the readme:
```
// build.gradle
modrinth {
    token = System.getenv("MODRINTH_TOKEN") // This is the default. Remember to have the MODRINTH_TOKEN environment variable set or else this will fail, or set it to whatever you want - just make sure it stays private!
    projectId = "my-project" // This can be the project ID or the slug. Either will work!
    versionNumber = "1.0.0" // You don't need to set this manually. Will fail if Modrinth has this version already
    versionType = "release" // This is the default -- can also be `beta` or `alpha`
    uploadFile = jar // With Loom, this MUST be set to `remapJar` instead of `jar`!
    gameVersions = ["1.18", "1.18.1"] // Must be an array, even with only one version
    loaders = ["fabric"] // Must also be an array - no need to specify this if you're using Loom or ForgeGradle
    dependencies { // A special DSL for creating dependencies
        // scope.type
        // The scope can be `required`, `optional`, `incompatible`, or `embedded`
        // The type can either be `project` or `version`
        required.project "fabric-api" // Creates a new required dependency on Fabric API
        optional.version "sodium", "mc1.19.3-0.4.8" // Creates a new optional dependency on this specific version of Sodium
    }
}
```
The properties listed here are corresponding to the Property variables within the ModrinthExtension class. It does not matter that they are private.
So `modrinth.uploadFile = jar` will fail to set the file property which is getting used in the `CreateVersionRequest`.

**Comment by ExpensiveKoala** [comment]
https://github.com/modrinth/minotaur/blob/c9dc1f2a77b04301047724049557cd183226a3ce/src/main/java/com/modrinth/minotaur/TaskModrinthUpload.java#L161 is adding the `file` property to the list of files being sent in the request, and a few lines down you can see the `additionalFiles` being added. What you don't see is the `legacyUploadFile` being added to the list.

**Comment by triphora** [comment]
The legacy file is set as `file`'s default convention: https://github.com/modrinth/minotaur/blob/c9dc1f2a77b04301047724049557cd183226a3ce/src/main/java/com/modrinth/minotaur/ModrinthExtension.java#L57

> The properties listed here are corresponding to the Property variables within the ModrinthExtension class. It does not matter that they are private.

No, the properties correspond to the get methods. Groovy automatically strips the get prefixes so that they *look like* you're setting the field, but I don't believe it is actually setting the field. Try setting a `legacyUploadFile` field.

Are you saying that this breaks stuff based on your review of this code or are you saying it breaks stuff because it broke one of your builds? The fact that eight days have gone by without any reports of breakages makes me think it's the former.

**Comment by ExpensiveKoala** [comment]
> Are you saying that this breaks stuff based on your review of this code or are you saying it breaks stuff because it broke one of your builds? The fact that eight days have gone by without any reports of breakages makes me think it's the former.

I am currently debugging a separate issue, but updating from 2.7.1->2.7.2 changes the error message from what I am working on to `> Cannot query the value of extension 'modrinth' property 'file' because it has no value available.`
Looking into it made me believe the reason the `file` property has no value available is because the `uploadFile` property doesn't work as intended. You can see my build.gradle here: https://github.com/ExpensiveKoala/Clear-Water/blob/master/build.gradle#L37-L55

If you want, I can open a separate issue for this error I am experiencing.


Edit: Seems I was wrong. In 2.7.1 the error message was that gameVersions was not set. 2.7.2 it was the above message. Turns out both error messages went away when I explicitly set the token property.

**Pull request merged**
